# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_q', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='post_q.Course'),
        ),
    ]
