# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_q', '0002_auto_20170425_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='./file/files'),
        ),
    ]
