# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_time', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='whu',
            options={'permissions': (('has_publish_signin', 'Can publish'), ('has_delete_signin', 'Delete Sign in'))},
        ),
    ]
